; ELRS Transmitter for ESP32-WROOM
; Computer (UART CRSF) -> TX -> RF (ELRS) -> off-the-shelf RX -> FC

[env:elrs_tx]
platform = espressif32@^6.5.0
board = esp32dev
framework = arduino
build_flags =
  -DBUILD_ELRS_TX
  -DCORE_DEBUG_LEVEL=1
build_src_filter =
  +<*>
  -<elrs_rx.cpp>
lib_deps =
  jgromes/RadioLib@^6.2.0
monitor_speed = 115200
